spring:
  datasource:
    jdbc-url: jdbc:mysql://api.dubble.at/dubble?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: dubble
    password: xxx
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  mail:
    host: mail.dubble.at
    username: service@dubble.at
    password: xxx
    sender: office@dubble.at

media-upload:
  image-path: "/mounted/img"
  video-path: "/mounted/video"
  pdf-path: "/mounted/pdf"

web-domain: "https://go.dubble.at"
cms-domain: "https://cms.dubble.at"
api-domain: "https://api.dubble.at"
